[config]
reload_apps = true

# Basic Stuff

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type","center", "--namespace", "wallpaper"]
set = false

# [templates.rofi]
# input_path = "~/.config/matugen/templates/rofi-colors.rasi"
# output_path = "~/.config/rofi/colors.rasi"

# # GTK

# Gradience for proper Material 3 theming of GTK4/libadwaita apps
[templates.gradience]
input_path = "~/.config/matugen/templates/gradience.json"
output_path = "~/.cache/matugen/gradience.json"
post_hook = "gradience-cli apply -p ~/.cache/matugen/gradience.json --gtk both"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
# # QT

[templates.qt5ct]
input_path = "~/.config/matugen/templates/qtct-colors.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "~/.config/matugen/templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

# # Terminals

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.cache/ags/user/generated/kitty-colors.conf"
post_hook = "kitty @ load-config"

# [templates.starship]
# input_path = "~/.config/matugen/templates/starship-colors.toml"
# output_path = "~/.config/starship.toml"
# post_hook = "starship init zsh > ~/.zshrc"

# # User Defined Apps <WIP>
#     # you can define each used app / fork eg.discord by changing their relative paths

# [templates.heroic]
# input_path = "~/.config/matugen/templates/heroic-theme.css"
# output_path = "~/.config//heroic-colors.css"

# [templates.Telegram]
# input_path = "~/.config/matugen/templates/telegram-colors.tdesktop-theme"
# output_path = "~/.config/telegram-desktop/themes/material-you.tdesktop-theme"

[templates.vencord]
input_path = "~/.config/matugen/templates/discord.css"
output_path = "~/.config/vesktop/themes/HyprLuna.css"

 [templates.obsidian]
 input_path = "~/.config/matugen/templates/obsidian.css"
 output_path = "~/Documents/JP/.obsidian/themes/Border/theme.css"

[templates.vscode]
input_path = "~/.config/matugen/templates/hyprlunavsc.json"
output_path = "~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.zen]
input_path = "~/.config/matugen/templates/userChrome.css"
output_path = "~/.zen/yak8abkd.Default (release)/chrome/userChrome.css"

# Kvantum for Material 3 theming of Qt apps
[templates.kvantum]
input_path = "~/.config/matugen/templates/kvantum.kvconfig"
output_path = "~/.config/Kvantum/MaterialAdw/MaterialAdw.kvconfig"

[templates.kvantum_svg]
input_path = "~/.config/matugen/templates/kvantum.svg"
output_path = "~/.config/Kvantum/MaterialAdw/MaterialAdw.svg"

# [templates.nvchad]
# input_path = "~/.config/matugen/templates/nvluna.lua"
# output_path = "~/.config/nvim/lua/themes/nvluna.lua"
# post_hook = "touch ~/.config/nvim/lua/themes/nvluna.lua"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-color.json"
output_path = "~/.config/quickshell/common/Colors.json"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = '~/.config/fuzzel/colors.ini'
